/*  PUT YOUR MELODY HERE IS FORM OF "NOTES_XX".
 * ( eg. NOTE_C5,NOTE_E5,NOTE_G5,NOTE_C6).
 *  NOTE_REST IS FOR EMPTY NOTE(RESTS).
 *  THIS SEQUENCE IS FOR BUZZER 2.
 */

int melody7[]= { 
NOTE_REST,
};
